In [1]:
import numpy as np #import the numpy library

In [2]:
arr = np.array([-1, 2, 5], dtype = np.float32)
print(repr(arr))

# dtype manually casts the array to a specified type

array([-1.,  2.,  5.], dtype=float32)


In [4]:
#Arrays

arr = np.array([[0, 1, 2], [3, 4, 5]],
               dtype = np.float32)
print(repr(arr))

#if the arrays are mixed types, all integers will be casted to floating equivs

arr = np.array([0, 0.1, 2])
print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)
array([0. , 0.1, 2. ])


In [6]:
#Copying

a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


In [8]:
# Casting 

arr = np.array([0, 1, 2])
print(arr.dtype)

arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


In [9]:
# NaN values

arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

np.array([np.nan, 1, 2], dtype = np.float32)
# np.nan cannot take on integer type

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


array([nan,  1.,  2.], dtype=float32)

In [10]:
# Infinity values

print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

True
array([inf,  5.])
array([-inf,   1.])


In [11]:
# Ranged Data

arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [12]:
#Evenly Spaced array of values
arr = np.linspace(5, 11, num = 4)
print(repr(arr))

arr = np.linspace(5, 11, num = 4, endpoint = False)
print(repr(arr))

arr = np.linspace(5, 11, num = 4, dtype = np.int32)
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11], dtype=int32)


In [13]:
# Reshaping Data

arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New Shape: {}'.format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New Shape: {}'.format(reshaped_arr.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New Shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New Shape: (2, 2, 2)


In [14]:
#Flattening and Reshaping

arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()

print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


In [15]:
# Transposing the data
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)

print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape : {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape : (2, 4)


In [18]:
# Zeroes and Ones

arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype = np.int32)
print(repr(arr))

arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype = np.int32)))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)
array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


In [2]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

print(repr(arr + 1))
print(repr(arr - 1.2))
print(repr(arr * 2))
print(repr(arr / 2))
print(repr(arr // 2))
print(repr(arr * 2))
print(repr(arr ** 0.5))

array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]])
array([[2, 4],
       [6, 8]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


In [3]:
def f2c(temps):
    return (5/9) * (temps - 32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

# Note numpy arrays does not change the original array

Celsius: array([  0., -20., -10., -40.])


In [4]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.array(arr)))
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
print(repr(np.log(arr2)))
print(repr(np.log10(arr2)))

array([[1, 2],
       [3, 4]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


In [5]:
# Powers of Arrays
arr = np.array([[1, 2], [3, 4]])
print(repr(np.power(3, arr)))

arr2 = np.array([[10.2, 4], [3, 5]])
print(repr(np.power(arr2, arr)))

array([[ 3,  9],
       [27, 81]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


In [6]:
# Matrix Multiplication
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


In [9]:
# Random Integers
print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high = 6))

random_arr = np.random.randint(-3, high = 14, size = (2, 2))

print(repr(random_arr))

2
4
5
array([[ 4, -2],
       [12,  9]])


In [10]:
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high = 100, size = (2, 2))
print(repr(random_arr))

np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high = 100, size = (2, 2))
print(repr(random_arr))

np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high = 100, size = (2, 2))
print(repr(random_arr))

5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
5
array([[15, 75],
       [12, 78]])


In [11]:
vec = np.array([1, 2, 3, 4, 5])

np.random.shuffle(vec)
print(repr(vec))

np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))

array([3, 4, 2, 5, 1])
array([5, 3, 4, 2, 1])
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])


In [12]:
# Distrbutions in NumPy
print(np.random.uniform())
print(np.random.uniform(low = -1.5, high = 2.2))
print(repr(np.random.uniform(size = 3)))
print(repr(np.random.uniform(low = -3.4, high = 5.9,
                             size = (2, 2))))

0.3132735169322751
0.4408281904196243
array([0.44345289, 0.22957721, 0.53441391])
array([[5.09984683, 0.85200471],
       [0.60549667, 5.33388844]])


In [13]:
print(np.random.normal())
print(np.random.normal(loc = 1.5, scale = 3.5))
print(repr(np.random.normal(loc = -2.4, scale = 4.0, size = (2, 2))))

0.7252740646272712
4.772112039383628
array([[ 2.07318791, -2.17754724],
       [-0.89337346, -0.89545991]])


In [14]:
# Custom Sampling
colors = ['red', 'blue', 'green']
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size = 2)))
print(repr(np.random.choice(colors, size = (2, 2), p = [0.8, 0.19, 0.01])))

green
array(['blue', 'red'], dtype='<U5')
array([['red', 'red'],
       ['blue', 'red']], dtype='<U5')


In [15]:
# Array Accessing
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

arr = np.array([[6, 3], [0, 2]])
print(repr(arr[0]))

1
5
array([6, 3])


In [18]:
# Indexing Arrays and Slicing

arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[:, -1]))
print(repr(arr[:, 1:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0, 1:]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([1, 2, 3, 4])
array([4, 5])
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


In [20]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 11]])
print(np.argmin(arr[0]))
print(np.argmax(arr[2]))
print(np.argmin(arr))

arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(repr(np.argmin(arr, axis=0)))
print(repr(np.argmin(arr, axis=1)))
print(repr(np.argmax(arr, axis=-1)))

2
2
5
array([2, 0, 1])
array([2, 2, 0])
array([1, 1, 1])


In [21]:
# Filtering Data

arr = np.array([[0, 2, 3],
                [1, 3, -6], 
                [-3, -2, 1]])
print(repr(arr == 3))
print(repr(arr > 0))
print(repr(arr != 1))
print(repr(~(arr != 1)))

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])
array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])


In [22]:
arr = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])
print(repr(np.isnan(arr)))

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])


In [23]:
print(repr(np.where([True, False, True])))

arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))

arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])
X_ind, y_ind = np.where(arr != 0)

print(repr(X_ind))
print(repr(y_ind))
print(repr(arr[X_ind, y_ind]))

(array([0, 2]),)
(array([1, 3]),)
array([0, 0, 1, 2])
array([1, 2, 0, 0])
array([ 2,  3,  1, -3])


In [25]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
negatives = np.array([[-2, -5], [-1, -8]])

np_filter = positives > 2
print(repr(np.where([np_filter, positives, negatives])))

np_filter = negatives > 0
print(repr(np.where(np_filter, positives, negatives)))

(array([0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([1, 1, 0, 0, 1, 1, 0, 0, 1, 1]), array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))
array([[-2, -5],
       [-1, -8]])


In [26]:
np_filter = np.array([[True, False], [False, True]])
positive = np.array([[1, 2], [3, 4]])
print(repr(np.where(np_filter, positives, -1)))

array([[ 1, -1],
       [-1,  4]])


In [27]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
print(repr(arr > 0))
print(np.any(arr > 0))
print(np.all(arr > 0))

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])
True
False


In [3]:
import numpy as np

arr = np.array([[-2, -1, -3],
                [4, 5, -6], 
                [3, 9, 1]])

has_positive = np.any(arr > 0, axis = 1)
print(has_positive)
print(repr(arr[np.where(has_positive)]))

[False  True  True]
array([[ 4,  5, -6],
       [ 3,  9,  1]])


In [4]:
# Statistics with NumPy

arr = np.array([[0, 72, 3],
                [1, 3, -60], 
                [-3, -2, 4]])
print(arr.min())
print(arr.max())
print(repr(arr.min(axis = 0)))
print(repr(arr.max(axis = -1)))

-60
72
array([ -3,  -2, -60])
array([72,  3,  4])


In [5]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(np.mean(arr))
print(np.var(arr))
print(np.median(arr))
print(repr(np.median(arr, axis = -1)))

2.0
977.3333333333334
1.0
array([ 3.,  1., -2.])


In [6]:
# Aggregation in NumPy
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(repr(np.cumsum(arr)))
print(repr(np.cumsum(arr, axis = 0)))
print(repr(np.cumsum(arr, axis = 1)))

array([ 0, 72, 75, 76, 79, 19, 16, 14, 18])
array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]])
array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]])


In [7]:
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])
arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])
print(repr(np.concatenate([arr1, arr2])))
print(repr(np.concatenate([arr1, arr2], axis = 1)))
print(repr(np.concatenate([arr2, arr1], axis = 1)))

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])
array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])
array([[-15,   6,   1,   0,  72,   3],
       [  8,   9,  -4,   1,   3, -60],
       [  5, -21,  18,  -3,  -2,   4]])
